#!/usr/bin/env sh

# load the scripting addon
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

alias yc='yabai -m config'
alias yr='yabai -m rule --add'

yc external_bar all:26:26

# global settings
yc mouse_follows_focus             off
yc focus_follows_mouse             off
yc window_placement                second_child
yc window_topmost                  off
yc window_shadow                   off
yc window_border                   on
yc window_border_placement         exterior
yc window_border_width             10
yc window_border_radius            10
yc active_window_border_color      0xB2EBDBB2
yc normal_window_border_color      0xB2282828
yc insert_window_border_color      0xB2EBDBB2
yc window_opacity                  off
yc split_ratio                     0.50
yc auto_balance                    off
yc mouse_modifier                  fn
yc mouse_action1                   move
yc mouse_action2                   resize

# general space settings
yc layout                          bsp
yc top_padding                     4
yc bottom_padding                  0
yc left_padding                    0
yc right_padding                   0
yc window_gap                      0

yc window_topmost                  on
yc window_shadow                   float

# Space labels
yabai -m space 1 --label "Primary"
yabai -m space 2 --label "Comms"
yabai -m space 3 --label "Tools"
yabai -m space 4 --label "Media"
yabai -m space 5 --label "Social"
yabai -m space 6 --label "Float"
yabai -m space 7 --label "Secondary"

# Space config
yc --space 6 layout float
yc --space 2 layout float


# Unmanaged
yr app="^System Preferences$"  manage=off border=off
yr app="Harvest"               manage=off border=off
yr app="ScreenFlow 9"          manage=off border=off

# Primary
yr app="Brave Browser"         space=8
yr app="kitty"                 space=1
yr app="Preview"               space=1
yr app="VimR"                  space=1
yr app="Simulator"             space=1
yr app="Skim"                  space=1

# Communication
yr app="Slack"                 space=2
yr app="Notability"            space=2
yr app="Microsoft Outlook"     space=2
yr app="Messages"              space=2

# Tools
yr app="Finder"                space=3
yr app="Microsoft Word"        space=3
yr app="Sequel Pro"            space=3
yr app="Postman"               space=3
yr app="Sourcetree"            space=3
yr app="Activity Monitor"      space=3
yr app="App Store"             space=3
yr app="WebTorrent"            space=3
yr app="Terminal"              space=3

# Media
yr app="Music"                 space=4
yr app="QuickTime Player"      space=4
yr app="VLC"                   space=4
yr app="Spotify"               space=4

# Social
yr app="Discord"               space=5
yr app="WhatsApp"              space=5

# Floating
yr app="^System Preferences$"  space=6
yr app="ScreenFlow 9"          space=6
